# Site settings
title: "<span>Kyle</span> Brumm"
# title: "Kyle Brumm :: Developer//Designer"
description: "Iowa based web developer and designer, with a focus on WordPress theme development."
# baseurl: ""

# Contact Variables
url: "http://kylebrumm.com"
email: kjbrum@msn.com
contact:
  email:
    url: "mailto:"
    username: "kjbrum@msn.com"
  github:
    url: "http://github.com/"
    username: "kjbrum"
  facebook:
    url: "http://facebook.com/"
    username: "kylebrumm"
  twitter:
    url: "http://twitter.com/"
    username: "kyle_brumm"
  dribbble:
    url: "http://dribbble.com/"
    username: "kjbrum"

# Exclude from the Jekyll build
exclude: ["node_modules", "gulpfile.js", "package.json"]

# Other Settings
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
permalink: pretty
