# Site settings
title: "Jekyll Fun"
# title: "Kyle Brumm :: Developer//Designer"
email: kjbrum@msn.com
description: "My new jekyll site for blogging."
# description: "Iowa based developer with a focus on WordPress theme development."
# baseurl: ""
# url: ""
twitter_username: kyle_brumm
github_username:  kjbrum
exclude: ["node_modules", "gulpfile.js", "package.json"]

# Build settings
markdown: kramdown
permalink: pretty
