# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Kyle Brumm
email: kjbrumm@gmail.com
description: Musings from development escapades.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kylebrumm.com" # the base hostname & protocol for your site
permalink: /:title

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      is_post: true

# Banner image
# banner_image: "path/to/image"

# Enable post images in banner (true|false)
post_banner_images: false

# Social Media
social:
  - name: Github
    icon: github
    url: http://github.com
    username: kjbrum
  - name: CodePen
    icon: codepen
    url: http://codepen.io
    username: kjbrum
  - name: Dribbble
    icon: dribbble
    url: http://dribbble.com
    username: kjbrum
  - name: Instagram
    icon: instagram
    url: http://instagram.com
    username: kyle.brumm
  - name: LinkedIn
    icon: linkedin
    url: http://linkedin.com/in
    username: kylebrumm
  - name: Twitter
    icon: twitter
    url: http://twitter.com
    username: kyle_brumm
  - name: 500px
    icon: 500px
    url: http://500px.com
    username: kjbrum
  - name: Facebook
    icon: facebook
    url: http://facebook.com
    username: kylebrumm

# Google Analytics
ga_id: UA-32465732-1

# Hotjar
hj_id: 267046

# FontAwesome
fa_id: 37dea3faf8

# Build settings
markdown: kramdown
